package com.propertyfile;

import java.io.IOException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import com.baseclass.Base_Class;
import com.pom.Account_Creation_Page;
import com.pom.Home_Page;
import com.pom.Order_Page;
import com.pom.Register_Account_Page;
import com.sdp.Page_Object_Manager;

public class Runner extends Base_Class{
	public static WebDriver driver = Base_Class.getBrowser("chrome");
	public static Page_Object_Manager pom = new Page_Object_Manager(driver);
	public static void main(String[] args) throws Throwable{
		String url = File_Reader_Manager.getInstanceFRM().getInstanceCR().getURL();
		getURL(url);
		clickOnElement(pom.getInstanceHp().getLogin_Button());
		String username = File_Reader_Manager.getInstanceFRM().getInstanceCR().getEmail();
		inputValueElement(pom.getInstanceAcp().getEmail(),username);
		clickOnElement(pom.getInstanceAcp().getSubmitButton());
		sleep(5000);		
		clickOnElement(pom.getInstanceRap().gettitle());
		String custfirstname = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCustfirstname();
		inputValueElement(pom.getInstanceRap().getCustomerFirstname(),custfirstname);
		String custlastname = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCustlastname();
		inputValueElement(pom.getInstanceRap().getCustomerLastname(),custlastname);
		String password = File_Reader_Manager.getInstanceFRM().getInstanceCR().getPassword();
		inputValueElement(pom.getInstanceRap().getPassword(),password);
		String getDay = File_Reader_Manager.getInstanceFRM().getInstanceCR().getDay();
		dropDown("byValue", pom.getInstanceRap().getDay(),getDay);
		String getMonth = File_Reader_Manager.getInstanceFRM().getInstanceCR().getMonth();
		dropDown("byVisibleText", pom.getInstanceRap().getMonth(),getMonth);
		String getYear = File_Reader_Manager.getInstanceFRM().getInstanceCR().getYear();
		dropDown("byIndex", pom.getInstanceRap().getYear(),getYear);		
		String getFirstname = File_Reader_Manager.getInstanceFRM().getInstanceCR().getFirstname();
		inputValueElement(pom.getInstanceRap().getFirstname(),getFirstname);
		String getLastname = File_Reader_Manager.getInstanceFRM().getInstanceCR().getLastname();
		inputValueElement(pom.getInstanceRap().getLastname(),getLastname);
		String getCompany = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCompany();
		inputValueElement(pom.getInstanceRap().getCompany(),getCompany);
		String getAddress = File_Reader_Manager.getInstanceFRM().getInstanceCR().getAddress();
		inputValueElement(pom.getInstanceRap().getAddress(),getAddress);
		String getCity = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCity();
		inputValueElement(pom.getInstanceRap().getCity(),getCity);
		String getState = File_Reader_Manager.getInstanceFRM().getInstanceCR().getState();
		dropDown("byVisibleText", pom.getInstanceRap().getState(),getState);
		String getPincode = File_Reader_Manager.getInstanceFRM().getInstanceCR().getPincode();
		inputValueElement(pom.getInstanceRap().getPostCode(),getPincode);
		String getMobilenum = File_Reader_Manager.getInstanceFRM().getInstanceCR().getMobilenum();
		inputValueElement(pom.getInstanceRap().getMobile(),getMobilenum);		
		clear(pom.getInstanceRap().getAliasAddress());
		String getAliasaddress = File_Reader_Manager.getInstanceFRM().getInstanceCR().getAliasaddress();
		inputValueElement(pom.getInstanceRap().getAliasAddress(),getAliasaddress);
		clickOnElement(pom.getInstanceRap().getRegisterAccountButton());		
		sleep(3000);
		actionsClass("moveto",pom.getInstanceOp().getCategory());
		actionsClass("click",pom.getInstanceOp().getDress());
		sleep(3000);
		actionsClass("moveto",pom.getInstanceOp().getSelectedDress());
		actionsClass("click",pom.getInstanceOp().getAddToCart());
		sleep(3000);
		clickOnElement(pom.getInstanceOp().getProceedCheckout());
		clickOnElement(pom.getInstanceOp().getSigninCheckout());
		clickOnElement(pom.getInstanceOp().getAddressCheckout());
		clickOnElement(pom.getInstanceOp().getTerms());
		clickOnElement(pom.getInstanceOp().getShippingCheckout());
		sleep(3000);
		clickOnElement(pom.getInstanceOp().getPaymentCheckout());
		sleep(3000);
		clickOnElement(pom.getInstanceOp().getConfirmOrder());
		sleep(3000);
		String screenshotlocation = File_Reader_Manager.getInstanceFRM().getInstanceCR().getScreenshotLocation();
		takeScreenshot(screenshotlocation);
		quit();
	}
}
